name: Deploy GH Pages

on:
  release:
    types:
      - released
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy GitHup Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          clean: true
          folder: doc/dist
          target-folder: doc
